export const actionTypes = {
  // datareducer actions
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  INITIAL_CATEGORIES: "INITIAL_CATEGORIES",
  INITIAL_VIDEOS: "INITIAL_VIDEOS",
  CATEGORY_ERROR: "CATEGORY_ERROR",
  VIDEO_ERROR: "VIDEO_ERROR",

  // auth reducer actions
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_DUMMY_DATA: "SET_DUMMY_DATA",
  CLEAR_FORM: "CLEAR_FORM",
  CHECK_LOGIN_STATE: "CHECK_LOGIN_STATE",
  LOGIN_FAILED: "LOGIN_FAILED ",
  LOGIN_SERVER_ERROR: "LOGIN_SERVER_ERROR",
};
