export const actionTypes = {
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  INITIAL_CATEGORIES: "INITIAL_CATEGORIES",
  INITIAL_VIDEOS: "INITIAL_VIDEOS",
  CATEGORY_ERROR: "CATEGORY_ERROR",
  VIDEO_ERROR: "VIDEO_ERROR",
};
